package response

import "sync"

var cnResponses = &sync.Map{}
var cnMessages = map[int]string{
	ErrUnknown:           "服务器异常",
	ErrDB:                "数据库错误",
	ErrUserPermissions:   "权限不足",
	ErrImSitePermissions: "此站点权限不足",
	ErrImSiteParmLimit:   "配置限制超过上限",
	ErrTaskBusy:          "当前任务正在进行中",
	ErrDataNotExists:     "查询数据不存在",

	ErrUnauthorized:    "请重新登录",
	ErrBadRequest:      "请求参数错误",
	ErrNotLogin:        "用户未登录,请登录",
	ErrNoPermission:    "无权访问",
	ErrFailRequest:     "请求失败，请重试",
	ErrWrongPassword:   "密码错误",
	ErrIpBlocked:       "网络IP异常,请联系接待",
	ErrRegisterBlocked: "注册入口已关闭,请联系接待",
	ErrDeviceIDBlocked: "设备ID异常,请联系接待",
	ErrNickNameUsed:    "当前昵称已经被使用",
	ErrMutePeriod:      "请输入正确的时间段,以-分割",

	//用户
	ErrLoginDenied:           "你无法登录，因为没有登录权限",
	ErrLoadUserInfo:          "获取数据失败，请重试",
	ErrBadPassword:           "密码长度需在6～16之间",
	ErrBadAccount:            "请正确输入账号",
	ErrBadPhoneNumPwd:        "手机号或密码错误",
	ErrBadPhoneNumber:        "请正确输入手机号",
	ErrUserIdNotExist:        "帐号不存在",
	ErrRegisterFailed:        "注册失败，请重试",
	ErrConfigPassword:        "设置密码失败，请重试",
	ErrUserFreeze:            "该账号已被冻结",
	ErrInviteCode:            "请输入邀请码",
	ErrVerificationCode:      "请验证图形验证码",
	ErrSmsCode:               "短信验证码为必输项",
	ErrSettingNotExist:       "配置信息不存在",
	ErrBadCode:               "验证码错误",
	ErrPhoneNumberExist:      "手机号已注册，不能重复注册",
	ErrUpdateAccount:         "设置密码失败，请重试",
	ErrVersionNotExist:       "未设置可用版本号",
	ErrVersionExist:          "版本号已经存在，不可再添加",
	ErrInviteCodeExist:       "邀请码已经存在，不可再添加",
	ErrVersionRepeat:         "该平台已经存在一个开启的版本",
	ErrBadAccountPwd:         "账号或密码错误",
	ErrBadInviteCode:         "请输入正确的邀请码",
	ErrUserNotFound:          "用户找不到",
	ErrDefaultFriendNotFound: "默认好友不存在",
	ErrBadCaptcha:            "图形验证码获取失败，请重试",
	ErrBadSmsFactory:         "获取短信厂商失败，请重试",
	ErrBadSmsSend:            "一分钟内验证码不能重复发送",
	ErrSmsSend:               "发送验证码失败",
	ErrSignLog:               "今日已签到",
	ErrUserConfig:            "用户配置不存在",
	ErrBadSignLog:            "签到记录不存在",
	ErrBadRequestType:        "请求参数的类型错误",
	ErrUserIdExist:           "帐号已经存在",
	ErrIPBlackListExist:      "IP黑名单已经存在",
	ErrDefaultFriendFound:    "默认好友已存在",
	ErrRoleNameExist:         "此角色描述已存在",
	ErrRoleKeyExist:          "此角色名称已存在",
	ErrSameAccount:           "重复账号无法创建",
	ErrShieldExist:           "敏感词已经存在，不可再添加",
	ErrPrivilegeUserExist:    "该用户已经是特权",
	ErrRegisterLimit:         "该设备已达到注册上限",
	ErrRegisterTimeLimit:     "该IP已达到注册上限",
	ErrSuggestion:            "投诉建议不存在",
	ErrBalanceNotEnough:      "账户余额不足",
	ErrRedPackSingleDisable:  "禁止发送个人红包",
	ErrPayPasswdWrong:        "支付密码错误",
	ErrRedPackTimeout:        "该红包已超过24小时。如已领取，可在钱包明细中查看",
	ErrPayPasswdAlreadySet:   "支付密码已设置，忘记请找回支付密码",
	ErrInvalidAccount:        "账号中不能包含特殊字符",
	ErrSameNickname:          "重复昵称无法创建",
	ErrIPWhiteListExist:      "IP白名单已经存在",
	ErrIPNotInWhiteList:      "IP不在白名单里",
	ErrUserFavImageExist:     "用户图片收藏已存在",
	ErrRedPackPreAmount:      "普通红包需设置单个红包金额",
	ErrRedPackReceive:        "红包领取失败",
	ErrRedPackReceiveFinish:  "红包已被领完",
	ErrRedPackReceiveRepeat:  "红包已领取，不能再次领",
	ErrCustomerUserExist:     "该用户已经是客服人员",
	ErrRegisterLen:           "账号不安全,不得少于四个字符",
	ErrAccountExist:          "账号已注册，不能重复注册",
	//好友
	ErrAlreadyIsFriend:      "对方已经是好友了",
	ErrFriendNotExist:       "好友不存在",
	ErrFriendCanNotSelf:     "不能添加自己为好友",
	ErrFriendSearchNotExist: "用户不存在，请重试",
	ErrFriendNormalNotAdd:   "不允许加好友",
	ErrFriendIsMax:          "好友数量达到上限",
	ErrFriendNormalNotDel:   "不允许删除好友",
	ErrFriendLabelExist:     "好友分组已经存在",
	ErrFriendLabelForbiden:  "默认分组不可修改",
	ErrFriendLabelDelete:    "默认分组不可删除",
	ErrFriendLabelLimit:     "分组数量超过最大限制",
	ErrFriendLabelNotExist:  "当前分组不存在",
	ErrFriendInBlack:        "被好友拒收",
	ErrFriendExistInBlack:   "你已经在好友的黑名单中，已无法添加好友",
	//群组
	ErrNotInGroup:           "用户没有在群组中",
	ErrGroupNotExist:        "群组不存在",
	ErrGroupNotMember:       "群内没有成员",
	ErrApplyNotFound:        "申请不存在",
	ErrApplyDone:            "申请已被处理，不能重复审核",
	ErrAlreadyInGroup:       "用户已经在群组中",
	ErrOwnerCanNotQuit:      "群主不能退群",
	ErrSetOwnerOnlyAdmin:    "只能设置管理员为群主",
	ErrFuncRunning:          "其他管理员正在执行该操作，请稍后再试！",
	ErrCloseQuit:            "当前群禁止退群",
	ErrGroupMemberMax:       "群成员已满",
	ErrGroupMemberOutMax:    "群成员将超过最大数量",
	ErrGroupNormalNotJoin:   "普通用户不允许加群",
	ErrGroupIsMax:           "创建的群达到上限",
	ErrGroupNormalNotCreate: "普通用户不允许创建群聊",
	ErrGroupMuteAll:         "当前群体禁言",
	ErrGroupMuteAllPeriod:   "当前在禁言时间段",
	ErrGroupMuteUser:        "您已被禁言",

	//聊天
	ErrMsgSendRunning:    "其他管理员正在执行该操作，请稍后再试！",
	ErrChatRTCNotFound:   "通话不存在",
	ErrChatRTCStatus:     "通话状态异常",
	ErrChatRTCBusy:       "通话忙",
	ErrChatRTCTargetBusy: "对方通话忙",
	ErrChatRTCUser:       "通话用户不合法",
	ErrChatRTCDevice:     "通话设备不合法",
	ErrChatRTCNetworkBad: "通话网络不佳",
	ErrChatRTCAbort:      "通话中断",
	ErrChatRevoke:        "该消息无法撤销",
	ErrChatTooMuch:       "发送消息太频繁",

	//联系人
	ErrTagExists:          "tag已经存在",
	ErrTagNotExists:       "tag不存在",
	ErrTagFriendNotExists: "好友不在tag中",
	ErrTagFriendExists:    "好友已在tag中",

	//发现-加盟商
	ErrShopExists:           "店铺已存在或者正在审批中",
	ErrShopNotExists:        "店铺不存在",
	ErrInviteCodeExists:     "邀请码已经存在，请重试",
	ErrInviteCodeNotExists:  "邀请码不存在，请重试",
	ErrShopTeamMemberExists: "团队成员已存在，无需重复加入",
	ErrShopExSelf:           "不能加入自己创建的团队",
}

func init() {
	for code, msg := range cnMessages {
		cnResponses.Store(code, msg)
	}
}
