package response

import "sync"

var enResponses = &sync.Map{}
var enMessages = map[int]string{
	ErrUnknown:           "server error",
	ErrDB:                "database error",
	ErrUserPermissions:   "Insufficient permissions",
	ErrImSitePermissions: "This site has insufficient permissions",
	ErrImSiteParmLimit:   "Configuration limit exceeded upper limit",
	ErrTaskBusy:          "current task in progress",
	ErrDataNotExists:     "Query data does not exist.",

	ErrUnauthorized:    "please login again",
	ErrBadRequest:      "request parameter error",
	ErrNotLogin:        "The user is not login, please login",
	ErrNoPermission:    "not authorized to access",
	ErrFailRequest:     "request failed, please try again",
	ErrWrongPassword:   "password error",
	ErrIpBlocked:       "the network IP is abnormal, please contact customer service",
	ErrRegisterBlocked: "the registration entry has been closed, please contact customer service",
	ErrDeviceIDBlocked: "the device ID is abnormal, please contact customer service",
	ErrNickNameUsed:    "the current nickname is already in use",
	ErrMutePeriod:      "please enter the correct time period, separated by -",

	//用户
	ErrLoginDenied:           "you cannot log in because you do not have login permissions",
	ErrLoadUserInfo:          "failed to get data, please try again",
	ErrBadPassword:           "the password length must be between 6 and 16",
	ErrBadAccount:            "please enter the account number correctly",
	ErrBadPhoneNumPwd:        "mobile number or password is wrong",
	ErrBadPhoneNumber:        "please enter the mobile number correctly",
	ErrUserIdNotExist:        "account does not exist",
	ErrRegisterFailed:        "registration failed, please try again",
	ErrConfigPassword:        "failed to set password, please try again",
	ErrUserFreeze:            "the account has been frozen",
	ErrInviteCode:            "please enter the invitation code",
	ErrVerificationCode:      "please verify the graphic verification code",
	ErrSmsCode:               "SMS verification code is mandatory",
	ErrSettingNotExist:       "configuration information does not exist",
	ErrBadCode:               "verification code error",
	ErrPhoneNumberExist:      "the mobile phone number has already been registered and cannot be registered again",
	ErrUpdateAccount:         "failed to set password, please try again",
	ErrVersionNotExist:       "no version number available",
	ErrVersionExist:          "the version number already exists and cannot be added",
	ErrInviteCodeExist:       "the invitation code already exists and cannot be added",
	ErrVersionRepeat:         "an open version already exists for this platform",
	ErrBadAccountPwd:         "incorrect username or password",
	ErrBadInviteCode:         "please enter the correct invitation code",
	ErrUserNotFound:          "user not found",
	ErrDefaultFriendNotFound: "default friend does not exist",
	ErrBadCaptcha:            "failed to obtain graphic verification code, please try again",
	ErrBadSmsFactory:         "failed to get SMS vendor, please try again",
	ErrBadSmsSend:            "the verification code cannot be sent repeatedly within one minute",
	ErrSmsSend:               "failed to send verification code",
	ErrSignLog:               "signed in today",
	ErrUserConfig:            "user configuration does not exist",
	ErrBadSignLog:            "Check-in record does not exist",
	ErrBadRequestType:        "wrong type of request parameter",
	ErrUserIdExist:           "account already exists",
	ErrIPBlackListExist:      "IP blacklist already exists",
	ErrDefaultFriendFound:    "default friend already exists",
	ErrRoleNameExist:         "this role description already exists",
	ErrRoleKeyExist:          "this role name already exists",
	ErrSameAccount:           "duplicate account cannot be created",
	ErrShieldExist:           "sensitive words already exist, cannot be added",
	ErrPrivilegeUserExist:    "the user is already privileged",
	ErrRegisterLimit:         "the device has reached the registration limit",
	ErrRegisterTimeLimit:     "the IP has reached the registration limit",
	ErrSuggestion:            "complaint Suggestion None",
	ErrBalanceNotEnough:      "insufficient account balance",
	ErrRedPackSingleDisable:  "it is forbidden to send personal red envelopes",
	ErrPayPasswdWrong:        "wrong payment password",
	ErrRedPackTimeout:        "this red envelope has been over 24 hours. If you have already received it, you can check it in the wallet details",
	ErrPayPasswdAlreadySet:   "the payment password has been set, if you forget it, please retrieve the payment password",
	ErrInvalidAccount:        "the account number cannot contain special characters",
	ErrSameNickname:          "duplicate nickname cannot be created",
	ErrIPWhiteListExist:      "IP whitelist already exists",
	ErrIPNotInWhiteList:      "IP is not in the whitelist",
	ErrUserFavImageExist:     "user picture collection already exists",
	ErrRedPackPreAmount:      "ordinary red packet need to set the amount of red packet",
	ErrRedPackReceive:        "failed to receive the red packet",
	ErrRedPackReceiveFinish:  "the red packet has been received",
	ErrRedPackReceiveRepeat:  "the red packet has been received and cannot be claimed again",
	ErrCustomerUserExist:     "the user is already a customer service staff",
	ErrRegisterLen:           "the account number is not safe and must not be less than four characters",
	ErrAccountExist:          "the account has been registered and cannot be registered again",
	//好友
	ErrAlreadyIsFriend:      "the other party is already a friend",
	ErrFriendNotExist:       "friend does not exist",
	ErrFriendCanNotSelf:     "can't add myself as a friend",
	ErrFriendSearchNotExist: "user does not exist, please try again",
	ErrFriendNormalNotAdd:   "not allowed to add friends",
	ErrFriendIsMax:          "the number of friends has reached the upper limit",
	ErrFriendNormalNotDel:   "not allowed to delete friends",
	ErrFriendLabelExist:     "friends group already exists",
	ErrFriendLabelForbiden:  "the default group cannot be modified",
	ErrFriendLabelDelete:    "the default group cannot be deleted",
	ErrFriendLabelLimit:     "the number of groups exceeds the maximum limit",
	ErrFriendLabelNotExist:  "the current group does not exist",
	ErrFriendInBlack:        "friends refuse to accept",
	ErrFriendExistInBlack:   "You are already on your friend's blacklist and cannot add friends anymore",

	//群组
	ErrNotInGroup:           "user is not in the group",
	ErrGroupNotExist:        "group does not exist",
	ErrGroupNotMember:       "there are no members in the group",
	ErrApplyNotFound:        "application does not exist",
	ErrApplyDone:            "the application has been processed and cannot be reviewed again",
	ErrAlreadyInGroup:       "user is already in the group",
	ErrOwnerCanNotQuit:      "the group owner cannot leave the group",
	ErrSetOwnerOnlyAdmin:    "only administrators can be set as group owners",
	ErrFuncRunning:          "another administrator is performing this operation, please try again later!",
	ErrCloseQuit:            "the current group prohibits leaving the group",
	ErrGroupMemberMax:       "group members full",
	ErrGroupMemberOutMax:    "group members will exceed the maximum number",
	ErrGroupNormalNotJoin:   "ordinary users are not allowed to join groups",
	ErrGroupIsMax:           "the number of created groups has reached the upper limit",
	ErrGroupNormalNotCreate: "ordinary users are not allowed to create group chats",
	ErrGroupMuteAll:         "current Group Mute",
	ErrGroupMuteAllPeriod:   "during the mute",
	ErrGroupMuteUser:        "you have been muted",

	//聊天
	ErrMsgSendRunning:    "another administrator is performing this operation, please try again later!",
	ErrChatRTCNotFound:   "call does not exist",
	ErrChatRTCStatus:     "abnormal call status",
	ErrChatRTCBusy:       "call busy",
	ErrChatRTCTargetBusy: "the caller is busy",
	ErrChatRTCUser:       "call user is invalid",
	ErrChatRTCDevice:     "call device illegal",
	ErrChatRTCNetworkBad: "poor call network",
	ErrChatRTCAbort:      "call disconnected",
	ErrChatRevoke:        "this message cannot be undone",
	ErrChatTooMuch:       "sending messages too busy",

	//联系人
	ErrTagExists:       "Tag already exists",
	ErrTagNotExists:    "Friend not in tag",
	ErrTagFriendExists: "Friend already in tag",

	//发现-加盟商
	ErrShopExists:           "The store already exists or is in the process of approval",
	ErrShopNotExists:        "The Store does not exist",
	ErrInviteCodeExists:     "The invitation code already exists, please try again",
	ErrInviteCodeNotExists:  "The invitation code not exist",
	ErrShopTeamMemberExists: "Team member already exists, no need to repeat joining",
	ErrShopExSelf:           "Cannot join a team created by oneself",
}

func init() {
	for code, msg := range enMessages {
		enResponses.Store(code, msg)
	}
}
