package response

import "sync"

var japResponses = &sync.Map{}
var japMessages = map[int]string{
	ErrUnknown:           "サーバー例外",
	ErrDB:                "データベースエラー",
	ErrUserPermissions:   "権限が不十分です",
	ErrImSitePermissions: "このサイトには十分な権限がありません",
	ErrImSiteParmLimit:   "構成制限が上限を超えました",
	ErrTaskBusy:          "現在進行中のタスク",
	ErrDataNotExists:     "クエリデータが存在しません.",

	ErrUnauthorized:    "もう一度ログインしてください",
	ErrBadRequest:      "リクエストパラメータエラー",
	ErrNotLogin:        "ユーザーはログインしていません。ログインしてください",
	ErrNoPermission:    "アクセスなし",
	ErrFailRequest:     "リクエストが失敗しました。もう一度お試しください",
	ErrWrongPassword:   "間違ったパスワード",
	ErrIpBlocked:       "ネットワークIPが異常ですので受付までご連絡ください",
	ErrRegisterBlocked: "受付入口は閉まっておりますので受付までお問い合わせください",
	ErrDeviceIDBlocked: "デバイスIDが異常です。受付までご連絡ください。",
	ErrNickNameUsed:    "現在のニックネームはすでに使用されています",
	ErrMutePeriod:      "正しい期間を - で区切って入力してください。",

	//用户
	ErrLoginDenied:           "ログイン権限がないためログインできません",
	ErrLoadUserInfo:          "データの取得に失敗しました。もう一度お試しください。",
	ErrBadPassword:           "パスワードの長さは 6 ～ 16 でなければなりません",
	ErrBadAccount:            "口座番号を正しく入力してください",
	ErrBadPhoneNumPwd:        "携帯電話番号またはパスワードが間違っています",
	ErrBadPhoneNumber:        "携帯電話番号を正しく入力してください",
	ErrUserIdNotExist:        "アカウントが存在しません",
	ErrRegisterFailed:        "登録に失敗しました。もう一度お試しください",
	ErrConfigPassword:        "パスワードの設定に失敗しました。もう一度お試しください。",
	ErrUserFreeze:            "アカウントが凍結されました",
	ErrInviteCode:            "招待コードを入力してください",
	ErrVerificationCode:      "グラフィック確認コードを確認してください",
	ErrSmsCode:               "SMS認証コードは必須です",
	ErrSettingNotExist:       "構成情報が存在しません",
	ErrBadCode:               "認証コードエラー",
	ErrPhoneNumberExist:      "携帯電話番号はすでに登録されているため、再度登録することはできません",
	ErrUpdateAccount:         "パスワードの設定に失敗しました。もう一度お試しください。",
	ErrVersionNotExist:       "利用可能なバージョン番号がありません",
	ErrVersionExist:          "バージョン番号はすでに存在するため追加できません",
	ErrInviteCodeExist:       "招待コードはすでに存在するため追加できません",
	ErrVersionRepeat:         "このプラットフォームにはオープン バージョンがすでに存在します",
	ErrBadAccountPwd:         "ユーザーネームまたはパスワードが違います",
	ErrBadInviteCode:         "正しい招待コードを入力してください",
	ErrUserNotFound:          "ユーザーが見つかりません",
	ErrDefaultFriendNotFound: "デフォルトの友達は存在しません",
	ErrBadCaptcha:            "グラフィック確認コードを取得できませんでした。もう一度お試しください。",
	ErrBadSmsFactory:         "SMS ベンダーを取得できませんでした。もう一度お試しください。",
	ErrBadSmsSend:            "確認コードは 1 分以内に繰り返し送信することはできません",
	ErrSmsSend:               "確認コードの送信に失敗しました",
	ErrSignLog:               "今日サインインしました",
	ErrUserConfig:            "ユーザープロファイルが存在しません",
	ErrBadSignLog:            "チェックイン記録が存在しません",
	ErrBadRequestType:        "リクエストパラメータのタイプが間違っています",
	ErrUserIdExist:           "アカウントはすでに存在しています",
	ErrIPBlackListExist:      "IPブラックリストはすでに存在します",
	ErrDefaultFriendFound:    "デフォルトの友達はすでに存在します",
	ErrRoleNameExist:         "役割の説明が存在します",
	ErrRoleKeyExist:          "ロール名はすでに存在します",
	ErrSameAccount:           "重複したアカウントは作成できません",
	ErrShieldExist:           "センシティブな単語はすでに存在するため、追加できません",
	ErrPrivilegeUserExist:    "ユーザーはすでに特権を持っています",
	ErrRegisterLimit:         "デバイスが登録制限を超えています",
	ErrRegisterTimeLimit:     "IPが登録制限を超えています",
	ErrSuggestion:            "苦情の提案 なし",
	ErrBalanceNotEnough:      "口座残高不足",
	ErrRedPackSingleDisable:  "個人的な赤い封筒を送ることは禁止されています",
	ErrPayPasswdWrong:        "支払いパスワードエラー",
	ErrRedPackTimeout:        "赤い封筒は24時間以上経過しています。すでに受け取っている場合は、ウォレットの詳細で確認できます",
	ErrPayPasswdAlreadySet:   "支払いパスワードが設定されています。忘れた場合は、支払いパスワードを取得してください",
	ErrInvalidAccount:        "アカウントに特殊文字を含めることはできません",
	ErrSameNickname:          "重複したニックネームを作成できませんでした",
	ErrIPWhiteListExist:      "IP ホワイトリストはすでに存在します",
	ErrIPNotInWhiteList:      "IP がホワイトリストに含まれていません",
	ErrUserFavImageExist:     "ユーザーの写真がお気に入りに追加されました",
	ErrRedPackPreAmount:      "通常の赤い封筒は赤い封筒の量を設定する必要があります",
	ErrRedPackReceive:        "赤い封筒を受け取ることができませんでした",
	ErrRedPackReceiveFinish:  "赤い封筒が届きました",
	ErrRedPackReceiveRepeat:  "赤い封筒を受け取ったため、再度受け取ることはできません",
	ErrCustomerUserExist:     "ユーザーはすでにカスタマーサービスです",
	ErrRegisterLen:           "口座番号は安全ではありません。4 文字未満にすることはできません",
	ErrAccountExist:          "アカウントは登録済みのため、再登録できません",
	//好友
	ErrAlreadyIsFriend:      "あなたはすでに友達です",
	ErrFriendNotExist:       "友達は存在しません",
	ErrFriendCanNotSelf:     "自分を友達として追加できません",
	ErrFriendSearchNotExist: "ユーザーが存在しません。もう一度お試しください。",
	ErrFriendNormalNotAdd:   "友達の追加は許可されていません",
	ErrFriendIsMax:          "フレンド数が上限に達しました",
	ErrFriendNormalNotDel:   "友達の削除は許可されていません",
	ErrFriendLabelExist:     "友達グループはすでに存在します",
	ErrFriendLabelForbiden:  "デフォルトのグループは変更できません",
	ErrFriendLabelDelete:    "デフォルトグループは削除できません",
	ErrFriendLabelLimit:     "グループ数が上限を超えています",
	ErrFriendLabelNotExist:  "現在のグループは存在しません",
	ErrFriendInBlack:        "友人が受け取りを拒否",
	ErrFriendExistInBlack:   "あなたはすでに親友のブラックリストにいて、友達を追加することはできません",

	//群组
	ErrNotInGroup:           "ユーザーはグループに属していません",
	ErrGroupNotExist:        "グループは存在しません",
	ErrGroupNotMember:       "グループにメンバーがいません",
	ErrApplyNotFound:        "アプリケーションが存在しません",
	ErrApplyDone:            "申請はすでに処理されており、再度審査することはできません",
	ErrAlreadyInGroup:       "ユーザーはすでにグループに属しています",
	ErrOwnerCanNotQuit:      "グループ所有者はグループを脱退できません",
	ErrSetOwnerOnlyAdmin:    "グループオーナーとして設定できるのは管理者のみです",
	ErrFuncRunning:          "別の管理者がこの操作を実行しています。後でもう一度試してください。",
	ErrCloseQuit:            "現在のグループはグループからの脱退を禁止しています",
	ErrGroupMemberMax:       "グループは満員です",
	ErrGroupMemberOutMax:    "グループメンバーが最大数を超えます",
	ErrGroupNormalNotJoin:   "一般ユーザーはグループを追加できません",
	ErrGroupIsMax:           "作成したグループ数が上限に達しました",
	ErrGroupNormalNotCreate: "通常のユーザーはグループ チャットを作成できません",
	ErrGroupMuteAll:         "現在のグループ禁止",
	ErrGroupMuteAllPeriod:   "現在禁止期間中です",
	ErrGroupMuteUser:        "あなたは禁止されました",

	//聊天
	ErrMsgSendRunning:    "別の管理者がこの操作を実行しています。後でもう一度試してください。",
	ErrChatRTCNotFound:   "呼び出しが存在しません",
	ErrChatRTCStatus:     "異常な通話状態",
	ErrChatRTCBusy:       "忙しい",
	ErrChatRTCTargetBusy: "相手は忙しいです",
	ErrChatRTCUser:       "呼び出し元のユーザーは無効です",
	ErrChatRTCDevice:     "無効な通話デバイス",
	ErrChatRTCNetworkBad: "通話ネットワークが貧弱",
	ErrChatRTCAbort:      "通話が切断されました",
	ErrChatRevoke:        "このメッセージは取り消すことができません",
	ErrChatTooMuch:       "メッセージを頻繁に送信しすぎる",

	//联系人
	ErrTagExists:          "タグは既に存在します",
	ErrTagNotExists:       "tagは存在しません",
	ErrTagFriendNotExists: "友達はtagにいない",
	ErrTagFriendExists:    "友達はすでにtagの中にいます",

	//发现-加盟商
	ErrShopExists:           "店舗はすでに存在するか、承認中です",
	ErrShopNotExists:        "店舗は存在しません",
	ErrInviteCodeExists:     "招待コードはすでに存在します。再試行してください",
	ErrInviteCodeNotExists:  "招待コードは存在しません。再試行してください",
	ErrShopTeamMemberExists: "チームメンバーは既に存在し、重複参加は必要ありません",
	ErrShopExSelf:           "自分で作成したチームに参加することはできません",
}

func init() {
	for code, msg := range japMessages {
		japResponses.Store(code, msg)
	}
}
